#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/cygdrive/d/CD_ROM/ADC_SoC/Demonstrations/SoC_FPGA/ADC_SoC_HIGH_SPEED_ADC_HPS/Quartus/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_adc_a', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_ADC_A_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_ADC_A_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_ADC_A_COMPONENT_NAME onchip_memory2_adc_a
#define ONCHIP_MEMORY2_ADC_A_BASE 0x0
#define ONCHIP_MEMORY2_ADC_A_SPAN 100000
#define ONCHIP_MEMORY2_ADC_A_END 0x1869f
#define ONCHIP_MEMORY2_ADC_A_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_ADC_A_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_ADC_A_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_ADC_A_DUAL_PORT 1
#define ONCHIP_MEMORY2_ADC_A_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_ADC_A_INIT_CONTENTS_FILE soc_system_onchip_memory2_adc_a
#define ONCHIP_MEMORY2_ADC_A_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY2_ADC_A_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_ADC_A_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_ADC_A_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_ADC_A_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_ADC_A_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_ADC_A_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_ADC_A_SIZE_VALUE 100000
#define ONCHIP_MEMORY2_ADC_A_WRITABLE 1
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16
#define ONCHIP_MEMORY2_ADC_A_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_adc_a

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1487592025

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x10040
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x1004f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 8
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x10080
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x1008f
#define DIPSW_PIO_IRQ 0
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 4
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x100c0
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x100cf
#define BUTTON_PIO_IRQ 1
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'onchip_memory2_adc_b', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_ADC_B_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_ADC_B_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_ADC_B_COMPONENT_NAME onchip_memory2_adc_b
#define ONCHIP_MEMORY2_ADC_B_BASE 0x20000
#define ONCHIP_MEMORY2_ADC_B_SPAN 100000
#define ONCHIP_MEMORY2_ADC_B_END 0x3869f
#define ONCHIP_MEMORY2_ADC_B_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_ADC_B_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_ADC_B_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_ADC_B_DUAL_PORT 1
#define ONCHIP_MEMORY2_ADC_B_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_ADC_B_INIT_CONTENTS_FILE soc_system_onchip_memory2_adc_b
#define ONCHIP_MEMORY2_ADC_B_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY2_ADC_B_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_ADC_B_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_ADC_B_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_ADC_B_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_ADC_B_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_ADC_B_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_ADC_B_SIZE_VALUE 100000
#define ONCHIP_MEMORY2_ADC_B_WRITABLE 1
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16
#define ONCHIP_MEMORY2_ADC_B_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_adc_b

/*
 * Macros for device 'TERASIC_AD9254_A', class 'TERASIC_AD9254'
 * The macros are prefixed with 'TERASIC_AD9254_A_'.
 * The prefix is the slave descriptor.
 */
#define TERASIC_AD9254_A_COMPONENT_TYPE TERASIC_AD9254
#define TERASIC_AD9254_A_COMPONENT_NAME TERASIC_AD9254_A
#define TERASIC_AD9254_A_BASE 0x40000
#define TERASIC_AD9254_A_SPAN 4
#define TERASIC_AD9254_A_END 0x40003

/*
 * Macros for device 'TERASIC_AD9254_B', class 'TERASIC_AD9254'
 * The macros are prefixed with 'TERASIC_AD9254_B_'.
 * The prefix is the slave descriptor.
 */
#define TERASIC_AD9254_B_COMPONENT_TYPE TERASIC_AD9254
#define TERASIC_AD9254_B_COMPONENT_NAME TERASIC_AD9254_B
#define TERASIC_AD9254_B_BASE 0x40010
#define TERASIC_AD9254_B_SPAN 4
#define TERASIC_AD9254_B_END 0x40013


#endif /* _ALTERA_HPS_0_H_ */
